// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	//tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
	//
	profileSidebar: [
		{
			type: "doc",
			label: "Overview",
			id: "intro",
		},
	],
	toolingSidebar: [
		{
			type: "doc",
			label: "Introduction",
			id: "documentation-tooling/intro",
		},
		{
			type: "category",
			label: "Getting Started",
			link: {
				type: "doc",
				id: "documentation-tooling/getting-started", // this doc acts as landing page
			},
			items: [
				{
					type: "autogenerated",
					dirName: "documentation-tooling/guides",
				},
			],
		},
	],
	apiSidebar: [
	{
		type: "doc",
		label: "Introduction",
		id: "api-documentation/intro",
	},
	{
		type: "doc",
		label: "Getting Started",
		id: "api-documentation/Getting-Started",
	},
	// Comment out the API Reference section since the files were deleted
	/*
	{
		type: "category",
		label: "API Reference",
		items: [
			{
				type: "category",
				label: "Chimoney",
				items: [
					{
						type: "doc",
						id: "api-documentation/reference/chimoney/check-wallet-balance",
					},
					{
						type: "doc",
						id: "api-documentation/reference/chimoney/send-money",
					},
					{
						type: "doc",
						id: "api-documentation/reference/chimoney/chimoney-demo-api",
					},
					{
						type: "doc",
						id: "api-documentation/reference/chimoney/get-transfer-status",
					},
				],
			},
		],
	},
	*/
],
};

export default sidebars;
