// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	//tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
	
	profileSidebar: [
		{
			type: "doc",
			label: "Overview",
			id: "about me",
		},
	],

	toolingSidebar: [
		{
			type: 'doc',
			label: 'Overview',
			id: 'documentation-tooling/intro',
		},
		{
			type: 'category',
			label: 'Getting Started',
			collapsed: false,
			items: [
				'documentation-tooling/quick-overview',
				'documentation-tooling/guides/browser-extension-installation',
				'documentation-tooling/guides/pwa-installation-guide',
			],
		},
	],

	apiSidebar: [
		{
			type: "doc",
			label: "Introduction",
			id: "api-documentation/intro",
		},
		{
			type: "doc",
			label: "Getting Started", 
			id: "api-documentation/getting-started",
		},
		{
			type: "category",
			label: "API Reference",
			items: [
				{
					type: "category",
					label: "Chimoney",
					items: [
						{
							type: "doc",
							id: "api-documentation/reference/chimoney/check-wallet-balance",
						},
						{
							type: "doc",
							id: "api-documentation/reference/chimoney/send-money", 
						},
						{
							type: "doc",
							id: "api-documentation/reference/chimoney/get-transfer-status",
						},
					],
				},
			],
		},
	],
	// Add the missing automationSidebar
	automationSidebar: [
		{
		  type: "doc",
		  label: "Introduction",
		  id: "automation-workflows/intro",
		},
		{
		  type: "doc", 
		  label: "Sample",
		  id: "automation-workflows/sample",
		},
	  ],
	aiDocumentationSidebar: [
		{
      type: 'doc',
      id: 'ai-documentation/intro', // This points to your intro.md file
      label: 'Overview'
    },
	{
		type: 'category',
      label: 'Project Deliverables',
      items: [
        'ai-documentation/model_card',
        'ai-documentation/ai_output', 
        'ai-documentation/final_doc',
        'ai-documentation/prompt_used',
        'ai-documentation/reflection',
	  ]
	}
	],
	devopsCloudSidebar: [
		{
	type: 'doc',
	id: 'devops-cloud/intro',
	label: 'Intro',
}, 
{
	type: 'category',
      label: 'Deploy a Docusauraus Site on Vercel',
      items: [
        'devops-cloud/overview',
        'devops-cloud/setup',
        'devops-cloud/step_by_step',
        'devops-cloud/troubleshooting',
        'devops-cloud/summary',
        'devops-cloud/reflection',
	  ]
}
	],
	web3DocumentationSidebar: [
		{
	type: 'doc',
	id: 'web3-documentation/intro',
	label: 'Intro',
}, 
{
	type: 'category',
      label: 'End User Guide',
      items: [
        'web3-documentation/user-guide',
        'web3-documentation/reflection',
	  ]
}
	],
};

export default sidebars;