openapi: 3.0.3
info:
  title: Chimoney Demo API
  version: 1.0.0
  description: Demo spec used to generate docs in Docusaurus
servers:
  - url: https://api.example.com
tags:
  - name: Wallet
    description: Balance and transfers
  - name: Transfers
    description: Send money and check status

paths:
  /wallet/balance:
    get:
      tags: [Wallet]
      summary: Check wallet balance
      responses:
        '200':
          description: Current balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: float
  /v1/info/mobile-money-codes:
    get:
      summary: Get list of supported mobile money codes
      tags:
        - Getting Started
      description: Returns the list of mobile money codes supported on Chimoney.
      operationId: get-list-of-supported-mobile-money-codes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                      example: Mpesa_UG
          headers: {} 

  /transfers/send:
    post:
      tags: [Transfers]
      summary: Send money
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [to, amount, currency]
              properties:
                to: { type: string, format: email }
                amount: { type: number }
                currency: { type: string, example: USD }
      responses:
        '201':
          description: Transfer created
          content:
            application/json:
              schema:
                type: object
                properties:
                  transferId: { type: string }

  /transfers/{id}/status:
    get:
      tags: [Transfers]
      summary: Get transfer status
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Status details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [pending, completed, failed]